name: cirujales_activity_6
description: CC 206 Unit 6 Activity - Profile & Pet App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.png
    - assets/images/pet.png
    - assets/audio/pet_sound.mp3